### ISSUE TITLE
Hello, could you please tell me which references these projects are based on?

### ISSUE THREAD

**Issue by PuhuanKing** [Flamisell/StewartPlatform#1]
My research direction is using a six-degree-of-freedom parallel platform for wave compensation. I am currently conducting preliminary research. I feel that your project is very suitable for beginners, and I would like to ask which specific references you referred to. Thank you for your response.

**Comment by AsioOtus055** [comment]
Hi!
I am happy to hear that you found useful some parts of my repository! I have written this class to resume a bit of everything that I have learned during my brief research on stewart platforms. I have updated this class privately over time and then I created this repository, therefore, I cannot remember clearly every paper that I have read but I can provide you a small list of useful sources from which you can better understand this type of parallel manipulator:

1) DESIGN AND IMPLEMENTATION OF STEWART PLATFORM ROBOT FOR ROBOTICS COURSE LABORATORY (https://core.ac.uk/download/pdf/322824733.pdf). 
This thesis helped me to start my studies, there is a clear explanation of Inverse Kinematics and matlab code posted at the end which I used to get a hang of the platform.

2) EFFICIENT COMPUTATION OF FORWARD KINEMATICS AND JACOBIAN MATRIX OF A STEWART PLATFORM-BASED MANIPULATOR (DOI: [10.1109/SECON.1991.147884](https://doi.org/10.1109/SECON.1991.147884)). 
Forward Kinematics was a bit of a problem at first. Due to the differences between parallel manipulators and serial manipulators, Inverse Kinematics can be easily calculated while Forward Kinematics usually need iterative algorithms. This  Newton-Raphson Method solved my problems (: 
(p.s. this method fails when the initial real configuration of the robot is at a steep angle )

3) Optimal design of a Stewart platform using the global transmission index under determinate constraint of workspace (DOI:[10.1177/1687814017720880](http://dx.doi.org/10.1177/1687814017720880)). 
This publication was very helpful for my purposes. In its section "_The evaluation indexes based on the Jacobian matrix_"  you can study abou the stewart's platform indexes to analyze it's performance in a specific configuration. In this case, to analyze the workspace you need to discretize the space and find the index for every configuration. If you want to design a platform based on power transmission which is not Jacobian dependent, you can also dive in into the following Screw Theory.  It seems easy at the beginning but translating that into code is a bit of a challenge.

4) Forward/inverse force transmission capability analyses of fully parallel manipulators (DOI:[10.1109/70.954767](http://dx.doi.org/10.1109/70.954767)) and The Kinetostatic Capability Analysis of Robotic Manipulators (https://web.archive.org/web/20031203151805id_/http://www.engr.ucr.edu:80/~hkim/Thesis_PDF/The%20Kinetostatic%20Capability%20Analysis%20of%20Robotic%20Manipulators.pdf).
This paper was useful to study force transmission analysis and velocity transmission analysis. 

5) SINGULARITY-FREE PATH PLANNING FOR THE STEWART PLATFORM MANIPULATOR (https://doi.org/10.1016/S0094-114X(97)00095-5). 
Here you can study about the singularities of a stewart platform. I don't think you will need them in your project but is good to know that they exist. Parallel manipulator's singularities are a problem because the platform can get mechanically stuck (https://www.youtube.com/watch?v=RxIMTVVb3bs). Generally, if your platform does not reach big angles in the workspace, you can close an eye on this :)

Some of the papers are open, others can be opened with Sci-Hub (https://www.sci-hub.wf/) by just pasting the DOI  ;-)

I hope this helps you in some way, if you have any questions or doubts feel free to contact me via mail (mrc.giacchetti@gmail.com).

Un abbraccio

**Comment by PuhuanKing** [comment]
Thank you very much for your list of references. I will read these articles later. Thank you for your reply.
